# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/

$ ->
  $('#pins').imagesLoaded ->
    $('#pins').masonry
      itemSelector: '.box'
      isFitWidth: true

$('body').keydown (e) ->
  if e.keyCode == 37
    # left arrow button was pressed => click on Next link
    document.getElementById('next_pin').click()
  else if e.keyCode == 39
    # right arrow button was pressed => click on Previous link
    document.getElementById('previous_pin').click()
  return
# ---
# generated by js2coffee 2.2.0 http://js2.coffee/

$('#fileUpload').on 'change', ->
  #Get count of selected files
  countFiles = $(this)[0].files.length
  imgPath = $(this)[0].value
  extn = imgPath.substring(imgPath.lastIndexOf('.') + 1).toLowerCase()
  image_holder = $('#image-holder')
  image_holder_div = $('#image-holder-div')
  image_holder.empty()
  if extn == 'gif' or extn == 'png' or extn == 'jpg' or extn == 'jpeg'
    if typeof FileReader != 'undefined'
      #loop for each file selected for uploaded.
      i = 0
      while i < countFiles
        reader = new FileReader

        reader.onload = (e) ->
          $('<img />',
            'src': e.target.result
            'class': 'thumb-image'
            'width': '200').appendTo image_holder
          return

        image_holder_div.show()
        reader.readAsDataURL $(this)[0].files[i]
        i++
    else
      image_holder_div.hide()
  else
    image_holder_div.hide()
  return

# ---
# generated by js2coffee 2.2.0