# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/

$ ->
  $('#pins').imagesLoaded ->
    $('#pins').masonry
      itemSelector: '.box'
      isFitWidth: true

$('body').keydown (e) ->
  if e.keyCode == 37
    # left arrow button was pressed => click on Next link
    document.getElementById('next_pin').click()
  else if e.keyCode == 39
    # right arrow button was pressed => click on Previous link
    document.getElementById('previous_pin').click()
  return
# ---
# generated by js2coffee 2.2.0 http://js2.coffee/
